name: .NET

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore Test
    - name: Build
      run: dotnet build Test --configuration Release --no-restore
    - name: Test
      run: dotnet test Test --configuration Release --no-build --verbosity normal
